- build.gradle
- elasticsearch-cloud-mesos/src/main/java/org/elasticsearch/discovery/mesos/MesosDiscovery.java
- elasticsearch-cloud-mesos/src/main/java/org/elasticsearch/discovery/mesos/MesosUnicastHostsProvider.java
- executor/src/main/java/org/apache/mesos/elasticsearch/executor/ElasticsearchExecutor.java
- gradle/quality.gradle
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/ElasticsearchScheduler.java
> Upgrade to Java 8

- README.md
> Description on how to import Shakepeare dataset

- Vagrantfile
Not sure how you guys access Mesos UI, when you run this project in Vagrant. This works for me.
> Added private network configuration of vagrant.

- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/ElasticsearchScheduler.java
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/State.java
This code implements the requirements as specified by the DCOS certification document, points 1 through 9.
Note that there is one outstanding issue, where the frameworkID does not appear to be used, even though it is specified.
> Implementation of DCOS certification requirements 1-9

- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/ElasticsearchScheduler.java
- scheduler/src/test/java/org/apache/mesos/elasticsearch/scheduler/ElasticsearchSchedulerTest.java
- system-test/src/test/resources/mesos-es/docker-compose.yml
Framework now uses single Zookeeper host.
> Removed master url

- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/ElasticsearchScheduler.java
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/Task.java
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/controllers/TasksController.java
- scheduler/src/main/resources/public/partials/tasks.html
- scheduler/src/test/java/org/apache/mesos/elasticsearch/scheduler/ElasticsearchSchedulerTest.java
> Added task states to the API and UI.

- scheduler/Dockerfile
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/Main.java
- scheduler/src/main/resources/public/app/config.js
- scheduler/src/main/resources/public/app/services.js
- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/Main.java
Angular port is still hardcoded.
> Management port is now configurable via -m flag

- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/controllers/ClusterController.java
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/controllers/TasksController.java
- scheduler/src/main/resources/public/app/services.js
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/StatusApiSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/TestBase.java
> Moved /tasks and /cluster endpoints to /v1

- scheduler/build.gradle
> Fix broken build docker image

- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ExecutorSystemTest.java
> Fix system test on Docker-Machine environments

- scheduler/src/main/resources/public/app/controllers.js
- scheduler/src/main/resources/public/app/services.js
- scheduler/src/main/resources/public/index.html
GUI can now run on path, e.g. http://localhost:8080/some/path
Needed for DCOS certification
Fixes #219
> Fixed GUI paths.

- scheduler/src/main/resources/public/app/controllers.js
Fixes missing TASK_STAGING mapping.
> Fixed GUI task states mapping.

- README.md
- scheduler/src/main/resources/public/index.html
- scheduler/src/main/resources/public/partials/cluster.html
- scheduler/src/main/resources/public/stylesheets/style.css
- scheduler/src/main/resources/public/stylesheets/style.less
This branch fixes several issues in GUI and adds support email link to GUI and documentation.
The email address is mesos-es@container-solutions.com. If we would like to invite someone who contacts us to Slack, we can do that (https://containersolutions.slack.com/admin/invites), but Slack has a funny limit of Single-Channel Guests: 5 times the number of paying users. That's why we decided to use email as the default means of contact for now.
Emails sent to this group are delivered to Frank, Lukasz, Phil, Martin, James, Pini and Jaroslav.
> GUI tweaks

- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/controllers/SearchProxyController.java
> Fixed search proxy URL encoding

- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/Configuration.java
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/FrameworkInfoFactory.java
- scheduler/src/test/java/org/apache/mesos/elasticsearch/scheduler/FrameworkInfoFactoryTest.java
- scheduler/start-scheduler.sh
- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/ElasticsearchSchedulerContainer.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/DataVolumesSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ElasticsearchNodesResponse.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/FrameworkRoleSystemTest.java
Fixes https://github.com/mesos/elasticsearch/issues/221
> Support custom Mesos framework role (DCOS certification requirement #13)

- system-test/build.gradle
- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/Main.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/DataRetrievableAllNodesSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/DataVolumesSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/DiscoverySystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/FrameworkRoleSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ReconciliationSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/SchedulerMainSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/TestBase.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ZookeeperFrameworkSystemTest.java
> Upgraded to Mini-Mesos 0.2.9

- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/state/ESTaskStatus.java
- scheduler/src/test/java/org/apache/mesos/elasticsearch/scheduler/state/ESTaskStatusTest.java
Fixes https://github.com/mesos/elasticsearch/issues/289
> Added finished to list of error state.

- scheduler/src/main/resources/public/index.html
> Updated h1 in GUI to display the ES cluster name.

- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/ElasticsearchScheduler.java
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/OfferStrategy.java
- scheduler/src/test/java/org/apache/mesos/elasticsearch/scheduler/ElasticsearchSchedulerTest.java
- scheduler/src/test/java/org/apache/mesos/elasticsearch/scheduler/OfferStrategyTest.java
> #292 offers method

- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/Main.java
- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/SeedDataContainer.java
- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/TasksResponse.java
> Updated system-test:main with mwldk/shakespeare-import seed data.

- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/TasksResponse.java
> Condition fix

- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/ElasticsearchScheduler.java
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/Main.java
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/cluster/ClusterMonitor.java
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/state/ClusterState.java
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/state/FrameworkState.java
- scheduler/src/test/java/org/apache/mesos/elasticsearch/scheduler/ElasticsearchSchedulerTest.java
- scheduler/src/test/java/org/apache/mesos/elasticsearch/scheduler/cluster/ClusterMonitorTest.java
- scheduler/src/test/java/org/apache/mesos/elasticsearch/scheduler/state/ESTaskStatusTest.java
> Removed Observable

- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/ElasticsearchSchedulerContainer.java
- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/Main.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/DataVolumesSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/FrameworkRoleSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ReconciliationSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/SchedulerMainSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/TestBase.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ZookeeperFrameworkSystemTest.java
Fixes issue where executors wouldn't start.
Please update mini-mesos to the latest commit, it adds ZK path customizer.
> Linking containers to scheduler

- commons/Dockerfile
- commons/build.gradle
- executor/Dockerfile
- scheduler/Dockerfile
Low hanging fruits of #165.
Basically I found that just adding what's needed by mesos is very difficult. `libmesos.so` has a hole boatload of other dependencies and eventually you'll end up adding everything that's installed by the official packages anyway.
> Shrink docker images

- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/Configuration.java
- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/ElasticsearchSchedulerContainer.java
- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/Main.java
- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/TasksResponse.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/DataRetrievableAllNodesSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/DataVolumesSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ExecutorSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/FrameworkRoleSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ReconciliationSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/SchedulerMainSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/StatusApiSystemTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/TestBase.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ZookeeperFrameworkSystemTest.java
Fixes #238 
Ready for review and merge
> Refactored system tests to use Configuration object 

- build.gradle
> Disabled pushing mesos/elasticsearch-base docker image on release.

- build.gradle
> Added latest tag to the docker images.

- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ScalingSystemTest.java
> Fixed instability of scaling system test,

- docs/index.md
> Replace gradle task build with buildDockerImage (fixes #441)

- docs/index.md
- executor/src/main/resources/elasticsearch.yml
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/Configuration.java
> Added docker/jar mode qualifications to CLI documentation.

- docs/index.md
> Added new jar mode example. Added link to GH releases.

- executor/src/main/java/org/apache/mesos/elasticsearch/executor/Configuration.java
- executor/src/main/java/org/apache/mesos/elasticsearch/executor/mesos/ElasticsearchExecutor.java
- executor/src/main/resources/elasticsearch.yml
- executor/src/test/java/org/apache/mesos/elasticsearch/executor/elasticsearch/ElasticsearchLauncherTest.java
- system-test/build.gradle
- system-test/src/main/java/org/apache/mesos/elasticsearch/systemtest/ESTasks.java
- system-test/src/main/resources/log4j.xml
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/RunAsJarSystemTest.java
- system-test/src/systemTest/resources/log4j.xml
Added system test for reading user custom yml files.
Fixes #465
> Default ES settings added first. User's overwrite. 

- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ScalingSystemTest.java
- system-test/src/systemTest/resources/log4j.xml
> Could not reproduce scale data bug but added system test

- executor/src/main/java/org/apache/mesos/elasticsearch/executor/mesos/ElasticsearchExecutor.java
> Add cluster yellow to list of valid run states.

- docs/index.md
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/Configuration.java
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/TaskInfoFactory.java
- scheduler/src/test/java/org/apache/mesos/elasticsearch/scheduler/TaskInfoFactoryTest.java
- system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/DifferentESVersionSystemTest.java
> Add ability to specify ES version.

- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/ResourceCheck.java
- scheduler/src/test/java/org/apache/mesos/elasticsearch/scheduler/ResourceCheckTest.java
> Add NPE check around resources. Add test.

- docs/index.md
- scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/Configuration.java
> Add format to user specified ports.
